### ISSUE TITLE
Not working anymore : Cannot find module 'date-fns'

### ISSUE THREAD

**Issue by stevebeauge** [estruyf/vscode-typescript-exportallmodules#23]
Hello,

The extension stopped to work recently. Menu entries are presents in the explorer view, but nothing happens when clicking on it.

Current installed version is 2.6.0.

Switching back to 2.5.0 restores the behavior.

In the VS code extension host logs I can see:

```
... other extension stuff ...

2023-08-31 11:38:15.320 [info] ExtensionService#_doActivateExtension eliostruyf.vscode-typescript-exportallmodules, startup: false, activationEvent: 'onStartupFinished'
2023-08-31 11:38:15.363 [error] Activating extension eliostruyf.vscode-typescript-exportallmodules failed due to an error:
2023-08-31 11:38:15.363 [error] Error: Cannot find module 'date-fns'
Require stack:
- c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\helpers\logger.js
- c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\commands\ExportAll.js
- c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\extension.js
- c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
- 
	at Module._resolveFilename (node:internal/modules/cjs/loader:1010:15)
	at s._resolveFilename (node:electron/js2c/utility_init:2:2740)
	at Module._load (node:internal/modules/cjs/loader:858:27)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\helpers\logger.js:5:20)
	at u._compile (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\commands\ExportAll.js:18:18)
	at u._compile (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\extension.js:14:21)
	at u._compile (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.i [as __$__nodeRequire] (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
	at r.rb (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:26597)
	at async Promise.all (index 0)
    
... other extension stuff ...


2023-08-31 11:40:21.517 [info] ExtensionService#_doActivateExtension eliostruyf.vscode-typescript-exportallmodules, startup: false, activationEvent: 'onStartupFinished'
2023-08-31 11:40:21.556 [error] Activating extension eliostruyf.vscode-typescript-exportallmodules failed due to an error:
2023-08-31 11:40:21.556 [error] Error: Cannot find module 'date-fns'
Require stack:
- c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\helpers\logger.js
- c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\commands\ExportAll.js
- c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\extension.js
- c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
- 
	at Module._resolveFilename (node:internal/modules/cjs/loader:1010:15)
	at s._resolveFilename (node:electron/js2c/utility_init:2:2740)
	at Module._load (node:internal/modules/cjs/loader:858:27)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\helpers\logger.js:5:20)
	at u._compile (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\commands\ExportAll.js:18:18)
	at u._compile (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\extension.js:14:21)
	at u._compile (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.i [as __$__nodeRequire] (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
	at r.rb (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:26597)
	at async Promise.all (index 0)
	
... other extension stuff ...

2023-08-31 11:46:00.155 [info] ExtensionService#_doActivateExtension eliostruyf.vscode-typescript-exportallmodules, startup: false, activationEvent: 'onStartupFinished'
2023-08-31 11:46:00.181 [error] Activating extension eliostruyf.vscode-typescript-exportallmodules failed due to an error:
2023-08-31 11:46:00.181 [error] Error: Cannot find module 'date-fns'
Require stack:
- c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\helpers\logger.js
- c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\commands\ExportAll.js
- c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\extension.js
- c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
- 
	at Module._resolveFilename (node:internal/modules/cjs/loader:1010:15)
	at s._resolveFilename (node:electron/js2c/utility_init:2:2740)
	at Module._load (node:internal/modules/cjs/loader:858:27)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\helpers\logger.js:5:20)
	at u._compile (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\commands\ExportAll.js:18:18)
	at u._compile (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\extension.js:14:21)
	at u._compile (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.i [as __$__nodeRequire] (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
	at r.rb (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:26597)
	at async Promise.all (index 0)

... other extension stuff ...	

2023-08-31 11:50:33.218 [info] ExtensionService#_doActivateExtension eliostruyf.vscode-typescript-exportallmodules, startup: false, activationEvent: 'onStartupFinished'

... other extension stuff ...

2023-08-31 11:51:52.338 [info] ExtensionService#_doActivateExtension eliostruyf.vscode-typescript-exportallmodules, startup: false, activationEvent: 'onStartupFinished'
2023-08-31 11:51:52.371 [error] Activating extension eliostruyf.vscode-typescript-exportallmodules failed due to an error:
2023-08-31 11:51:52.371 [error] Error: Cannot find module 'date-fns'
Require stack:
- c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\helpers\logger.js
- c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\commands\ExportAll.js
- c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\extension.js
- c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
- 
	at Module._resolveFilename (node:internal/modules/cjs/loader:1010:15)
	at s._resolveFilename (node:electron/js2c/utility_init:2:2740)
	at Module._load (node:internal/modules/cjs/loader:858:27)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\helpers\logger.js:5:20)
	at u._compile (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\commands\ExportAll.js:18:18)
	at u._compile (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
	at Object.<anonymous> (c:\Users\steve\.vscode\extensions\eliostruyf.vscode-typescript-exportallmodules-2.6.0\out\extension.js:14:21)
	at u._compile (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:28084)
	at f._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:25418)
	at C._load (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.i [as __$__nodeRequire] (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
	at r.rb (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:130:26597)
	at async Promise.all (index 0)
```

**Comment by estruyf** [comment]
Thanks @stevebeauge, that is interesting, as the dependency is also included in `2.5.0`. I'll check if I can reproduce the behavior and fix it.

**Comment by estruyf** [comment]
I configured the extension to generate bundles, ensuring it doesn't require dependencies. This should fix the issue.

**Comment by stevebeauge** [comment]
Works as expected now.

Thanks for the fix !
